<!DOCTYPE html>
<html lang="en-US">
  <head>
    <link rel="apple-touch-icon" sizes="180x180" href="content/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="content/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="content/favicon/favicon-16x16.png">
<link rel="manifest" href="content/favicon/site.webmanifest">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Noah Collaco" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 1</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume.pdf/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/new-post/">Project 1</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          May 6, 2020
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<pre class="r"><code>library(tidyverse)
library(readxl)
library(kableExtra)
library(GGally)
library(cluster)
Education &lt;- read_excel(&quot;Education2.xls&quot;, skip = 4)
RankedMeasureData &lt;- read_excel(&quot;2019 County Health Rankings Texas Data - v1_0.xls&quot;, 
    sheet = &quot;Ranked Measure Data&quot;)
AdditionalMeasureData &lt;- read_excel(&quot;2019 County Health Rankings Texas Data - v1_0.xls&quot;, 
    sheet = &quot;Additional Measure Data&quot;)</code></pre>
<p>This project uses data from the 2019 County Health Rankings for Texas and the USDA ERS Educational Attainment Data. These datasets are large so specific variables of County Name, % Obese, % Diabetic, Percent of a County with a Bachelors Degree, Median Household Income, and % Rural of a County were taken.</p>
<pre class="r"><code>TXEducation &lt;- Education %&gt;% filter(State == &quot;TX&quot;)
TXEducation &lt;- TXEducation %&gt;% rename(c(County = `Area name`))
partialdata &lt;- left_join(RankedMeasureData, TXEducation, by = &quot;County&quot;)
fulldata &lt;- left_join(partialdata, AdditionalMeasureData, by = &quot;County&quot;)
head(fulldata)</code></pre>
<pre><code>## # A tibble: 6 x 318
##   FIPS.x State.x County `Years of Poten~ `95% CI - Low..~ `95% CI - High.~
##   &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt;             &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1 48000  Texas   &lt;NA&gt;              6681.            6648.            6715.
## 2 48001  Texas   Ander~           10273.            9393.           11152.
## 3 48003  Texas   Andre~            7953.            6517.            9389.
## 4 48005  Texas   Angel~            9018.            8324.            9713.
## 5 48007  Texas   Arans~            9316.            7966.           10665.
## 6 48009  Texas   Archer            9446.            6731.           12161.
## # ... with 312 more variables: `Z-Score...7` &lt;dbl&gt;, `YPLL Rate (Black)` &lt;dbl&gt;,
## #   `YPLL Rate (Hispanic)` &lt;dbl&gt;, `YPLL Rate (White)` &lt;dbl&gt;, `%
## #   Fair/Poor` &lt;dbl&gt;, `95% CI - Low...12.x` &lt;dbl&gt;, `95% CI -
## #   High...13.x` &lt;dbl&gt;, `Z-Score...14` &lt;dbl&gt;, `Physically Unhealthy
## #   Days` &lt;dbl&gt;, `95% CI - Low...16` &lt;dbl&gt;, `95% CI - High...17` &lt;dbl&gt;,
## #   `Z-Score...18` &lt;dbl&gt;, `Mentally Unhealthy Days` &lt;dbl&gt;, `95% CI -
## #   Low...20` &lt;dbl&gt;, `95% CI - High...21` &lt;dbl&gt;, `Z-Score...22` &lt;dbl&gt;,
## #   Unreliable &lt;chr&gt;, `% LBW` &lt;dbl&gt;, `95% CI - Low...25` &lt;dbl&gt;, `95% CI -
## #   High...26` &lt;dbl&gt;, `Z-Score...27` &lt;dbl&gt;, `% LBW (Black)` &lt;dbl&gt;, `% LBW
## #   (Hispanic)` &lt;dbl&gt;, `% LBW (White)` &lt;dbl&gt;, `% Smokers` &lt;dbl&gt;, `95% CI -
## #   Low...32.x` &lt;dbl&gt;, `95% CI - High...33.x` &lt;dbl&gt;, `Z-Score...34` &lt;dbl&gt;, `%
## #   Obese` &lt;dbl&gt;, `95% CI - Low...36` &lt;dbl&gt;, `95% CI - High...37` &lt;dbl&gt;,
## #   `Z-Score...38` &lt;dbl&gt;, `Food Environment Index` &lt;dbl&gt;, `Z-Score...40` &lt;dbl&gt;,
## #   `% Physically Inactive` &lt;dbl&gt;, `95% CI - Low...42` &lt;dbl&gt;, `95% CI -
## #   High...43` &lt;dbl&gt;, `Z-Score...44` &lt;dbl&gt;, `% With Access` &lt;dbl&gt;,
## #   `Z-Score...46` &lt;dbl&gt;, `% Excessive Drinking` &lt;dbl&gt;, `95% CI -
## #   Low...48` &lt;dbl&gt;, `95% CI - High...49` &lt;dbl&gt;, `Z-Score...50` &lt;dbl&gt;, `#
## #   Alcohol-Impaired Driving Deaths` &lt;dbl&gt;, `# Driving Deaths` &lt;dbl&gt;, `%
## #   Alcohol-Impaired` &lt;dbl&gt;, `95% CI - Low...54` &lt;dbl&gt;, `95% CI -
## #   High...55` &lt;dbl&gt;, `Z-Score...56` &lt;dbl&gt;, `# Chlamydia Cases` &lt;dbl&gt;,
## #   `Chlamydia Rate` &lt;dbl&gt;, `Z-Score...59` &lt;dbl&gt;, `Teen Birth Rate` &lt;dbl&gt;, `95%
## #   CI - Low...61.x` &lt;dbl&gt;, `95% CI - High...62.x` &lt;dbl&gt;, `Z-Score...63` &lt;dbl&gt;,
## #   `Teen Birth Rate (Black)` &lt;dbl&gt;, `Teen Birth Rate (Hispanic)` &lt;dbl&gt;, `Teen
## #   Birth Rate (White)` &lt;dbl&gt;, `# Uninsured` &lt;dbl&gt;, `% Uninsured` &lt;dbl&gt;, `95%
## #   CI - Low...69` &lt;dbl&gt;, `95% CI - High...70` &lt;dbl&gt;, `Z-Score...71` &lt;dbl&gt;, `#
## #   Primary Care Physicians` &lt;dbl&gt;, `PCP Rate` &lt;dbl&gt;, `PCP Ratio` &lt;chr&gt;,
## #   `Z-Score...75` &lt;dbl&gt;, `# Dentists` &lt;dbl&gt;, `Dentist Rate` &lt;dbl&gt;, `Dentist
## #   Ratio` &lt;chr&gt;, `Z-Score...79` &lt;dbl&gt;, `# Mental Health Providers` &lt;dbl&gt;, `MHP
## #   Rate` &lt;dbl&gt;, `MHP Ratio` &lt;chr&gt;, `Z-Score...83` &lt;dbl&gt;, `Preventable Hosp.
## #   Rate` &lt;dbl&gt;, `Z-Score...85` &lt;dbl&gt;, `Preventable Hosp. Rate (Black)` &lt;dbl&gt;,
## #   `Preventable Hosp. Rate (Hispanic)` &lt;dbl&gt;, `Preventable Hosp. Rate
## #   (White)` &lt;dbl&gt;, `% Screened` &lt;dbl&gt;, `Z-Score...90` &lt;dbl&gt;, `% Screened
## #   (Black)` &lt;dbl&gt;, `% Screened (Hispanic)` &lt;dbl&gt;, `% Screened (White)` &lt;dbl&gt;,
## #   `% Vaccinated` &lt;dbl&gt;, `Z-Score...95` &lt;dbl&gt;, `% Vaccinated (Black)` &lt;dbl&gt;,
## #   `% Vaccinated (Hispanic)` &lt;dbl&gt;, `% Vaccinated (White)` &lt;dbl&gt;, `Cohort
## #   Size` &lt;dbl&gt;, `Graduation Rate` &lt;dbl&gt;, `Z-Score...101` &lt;dbl&gt;, `# Some
## #   College` &lt;dbl&gt;, Population.x &lt;dbl&gt;, `% Some College` &lt;dbl&gt;, `95% CI -
## #   Low...105` &lt;dbl&gt;, `95% CI - High...106` &lt;dbl&gt;, ...</code></pre>
<pre class="r"><code>project1 &lt;- fulldata %&gt;% select(County, `% Obese`, `% Diabetic`, 
    `Percent of adults with a bachelor&#39;s degree or higher, 2014-18`, 
    `Household Income`, `% Rural`)

project1 &lt;- project1 %&gt;% slice(2:255)
project1 &lt;- project1 %&gt;% rename(PercentObese = `% Obese`) %&gt;% 
    rename(PercentDiabetic = `% Diabetic`) %&gt;% rename(PercentBachelors = `Percent of adults with a bachelor&#39;s degree or higher, 2014-18`) %&gt;% 
    rename(Medianincome = `Household Income`) %&gt;% rename(pctRural = `% Rural`)
glimpse(project1)</code></pre>
<pre><code>## Rows: 254
## Columns: 6
## $ County           &lt;chr&gt; &quot;Anderson&quot;, &quot;Andrews&quot;, &quot;Angelina&quot;, &quot;Aransas&quot;, &quot;Arc...
## $ PercentObese     &lt;dbl&gt; 34.4, 32.2, 39.8, 31.8, 28.2, 29.4, 33.9, 29.9, 29...
## $ PercentDiabetic  &lt;dbl&gt; 10.7, 8.6, 13.6, 13.7, 11.3, 11.3, 11.6, 10.3, 9.7...
## $ PercentBachelors &lt;dbl&gt; 11.7, 10.4, 16.3, 21.7, 23.4, 23.2, 13.3, 23.5, 17...
## $ Medianincome     &lt;dbl&gt; 42412, 63451, 45318, 46970, 58311, 55337, 48636, 6...
## $ pctRural         &lt;dbl&gt; 67.063533, 16.502097, 43.082366, 27.260558, 88.988...</code></pre>
<p>To create the data set that was used for project one a left join was first performed with 2019 County Health Rankings Ranked Measure Data with data from the USDA Economic Research Service about educational attainment, which had already been filtered for TX counties only. This partial dataset was then joined, using a left join, to 2019 County Health Rankings Additional Measured data to in order to get median household income data.The 5 variables that were selected for the project were % Obesse, % Inactive, % Bachelors Degree, Median Household Income, and % Rural. Left Joins were used to keep all columns for both dataframs but only for the counties that matched between each dataframe.</p>
<pre class="r"><code>project1 %&gt;% arrange(-Medianincome) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 254
## Columns: 6
## $ County           &lt;chr&gt; &quot;Rockwall&quot;, &quot;Collin&quot;, &quot;Fort Bend&quot;, &quot;Kendall&quot;, &quot;Den...
## $ PercentObese     &lt;dbl&gt; 25.4, 26.9, 29.1, 26.3, 24.3, 31.4, 27.7, 29.9, 28...
## $ PercentDiabetic  &lt;dbl&gt; 9.6, 8.9, 9.3, 9.3, 8.3, 7.9, 9.5, 10.6, 9.9, 8.7,...
## $ PercentBachelors &lt;dbl&gt; 40.3, 51.7, 46.1, 40.9, 44.5, 41.1, 21.5, 29.7, 23...
## $ Medianincome     &lt;dbl&gt; 98442, 95394, 91661, 89637, 86462, 82131, 81018, 8...
## $ pctRural         &lt;dbl&gt; 16.035845, 5.242727, 5.535768, 58.159234, 6.905831...</code></pre>
<pre class="r"><code>project1 &lt;- project1 %&gt;% mutate(`Rural/Urban` = if_else(pctRural &gt; 
    50, &quot;Mostly Rural&quot;, &quot;Mostly Urban&quot;))
glimpse(project1)</code></pre>
<pre><code>## Rows: 254
## Columns: 7
## $ County           &lt;chr&gt; &quot;Anderson&quot;, &quot;Andrews&quot;, &quot;Angelina&quot;, &quot;Aransas&quot;, &quot;Arc...
## $ PercentObese     &lt;dbl&gt; 34.4, 32.2, 39.8, 31.8, 28.2, 29.4, 33.9, 29.9, 29...
## $ PercentDiabetic  &lt;dbl&gt; 10.7, 8.6, 13.6, 13.7, 11.3, 11.3, 11.6, 10.3, 9.7...
## $ PercentBachelors &lt;dbl&gt; 11.7, 10.4, 16.3, 21.7, 23.4, 23.2, 13.3, 23.5, 17...
## $ Medianincome     &lt;dbl&gt; 42412, 63451, 45318, 46970, 58311, 55337, 48636, 6...
## $ pctRural         &lt;dbl&gt; 67.063533, 16.502097, 43.082366, 27.260558, 88.988...
## $ `Rural/Urban`    &lt;chr&gt; &quot;Mostly Rural&quot;, &quot;Mostly Urban&quot;, &quot;Mostly Urban&quot;, &quot;M...</code></pre>
<p>Summary Statistics
Pivot wider and longer are used here to create organized tables of summary statistics. Pivot longer takes the names and values of the summary statistics into two columns called variable and stat. Pivot wider takes the names from variable and the values fro value to create a new column.</p>
<pre class="r"><code>project1 %&gt;% summarise_at(2:5, funs(mean = mean, sd = sd, var = var, 
    max = max, min = min))</code></pre>
<pre><code>## # A tibble: 1 x 20
##   PercentObese_me~ PercentDiabetic~ PercentBachelor~ Medianincome_me~
##              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1             30.1             10.8             18.7           49347.
## # ... with 16 more variables: PercentObese_sd &lt;dbl&gt;, PercentDiabetic_sd &lt;dbl&gt;,
## #   PercentBachelors_sd &lt;dbl&gt;, Medianincome_sd &lt;dbl&gt;, PercentObese_var &lt;dbl&gt;,
## #   PercentDiabetic_var &lt;dbl&gt;, PercentBachelors_var &lt;dbl&gt;,
## #   Medianincome_var &lt;dbl&gt;, PercentObese_max &lt;dbl&gt;, PercentDiabetic_max &lt;dbl&gt;,
## #   PercentBachelors_max &lt;dbl&gt;, Medianincome_max &lt;dbl&gt;, PercentObese_min &lt;dbl&gt;,
## #   PercentDiabetic_min &lt;dbl&gt;, PercentBachelors_min &lt;dbl&gt;,
## #   Medianincome_min &lt;dbl&gt;</code></pre>
<pre class="r"><code>project1 %&gt;% summarise_at(2:5, funs(mean = mean, sd = sd, var = var, 
    max = max, min = min)) %&gt;% pivot_longer(contains(&quot;_&quot;)) %&gt;% 
    separate(name, sep = &quot;_&quot;, into = c(&quot;variable&quot;, &quot;Stat&quot;)) %&gt;% 
    pivot_wider(names_from = &quot;variable&quot;, values_from = &quot;value&quot;) %&gt;% 
    arrange(Stat) %&gt;% kable()</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
Stat
</th>
<th style="text-align:right;">
PercentObese
</th>
<th style="text-align:right;">
PercentDiabetic
</th>
<th style="text-align:right;">
PercentBachelors
</th>
<th style="text-align:right;">
Medianincome
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
max
</td>
<td style="text-align:right;">
39.800000
</td>
<td style="text-align:right;">
15.100000
</td>
<td style="text-align:right;">
51.700000
</td>
<td style="text-align:right;">
98442.00
</td>
</tr>
<tr>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
30.066142
</td>
<td style="text-align:right;">
10.837795
</td>
<td style="text-align:right;">
18.714173
</td>
<td style="text-align:right;">
49346.70
</td>
</tr>
<tr>
<td style="text-align:left;">
min
</td>
<td style="text-align:right;">
21.500000
</td>
<td style="text-align:right;">
7.100000
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:right;">
28106.00
</td>
</tr>
<tr>
<td style="text-align:left;">
sd
</td>
<td style="text-align:right;">
2.383050
</td>
<td style="text-align:right;">
1.467402
</td>
<td style="text-align:right;">
7.536459
</td>
<td style="text-align:right;">
11993.75
</td>
</tr>
<tr>
<td style="text-align:left;">
var
</td>
<td style="text-align:right;">
5.678928
</td>
<td style="text-align:right;">
2.153269
</td>
<td style="text-align:right;">
56.798217
</td>
<td style="text-align:right;">
143850138.11
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>project1 %&gt;% group_by(`Rural/Urban`) %&gt;% summarise_at(2:5, funs(mean = mean, 
    sd = sd, var = var, max = max, min = min)) %&gt;% pivot_longer(contains(&quot;_&quot;)) %&gt;% 
    separate(name, sep = &quot;_&quot;, into = c(&quot;variable&quot;, &quot;Stat&quot;)) %&gt;% 
    pivot_wider(names_from = &quot;variable&quot;, values_from = &quot;value&quot;) %&gt;% 
    arrange(Stat) %&gt;% kable()</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
Rural/Urban
</th>
<th style="text-align:left;">
Stat
</th>
<th style="text-align:right;">
PercentObese
</th>
<th style="text-align:right;">
PercentDiabetic
</th>
<th style="text-align:right;">
PercentBachelors
</th>
<th style="text-align:right;">
Medianincome
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Mostly Rural
</td>
<td style="text-align:left;">
max
</td>
<td style="text-align:right;">
38.000000
</td>
<td style="text-align:right;">
15.100000
</td>
<td style="text-align:right;">
40.900000
</td>
<td style="text-align:right;">
8.963700e+04
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Urban
</td>
<td style="text-align:left;">
max
</td>
<td style="text-align:right;">
39.800000
</td>
<td style="text-align:right;">
13.800000
</td>
<td style="text-align:right;">
51.700000
</td>
<td style="text-align:right;">
9.844200e+04
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Rural
</td>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
29.904412
</td>
<td style="text-align:right;">
11.463235
</td>
<td style="text-align:right;">
17.472059
</td>
<td style="text-align:right;">
4.802908e+04
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Urban
</td>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
30.252542
</td>
<td style="text-align:right;">
10.116949
</td>
<td style="text-align:right;">
20.145763
</td>
<td style="text-align:right;">
5.086532e+04
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Rural
</td>
<td style="text-align:left;">
min
</td>
<td style="text-align:right;">
26.300000
</td>
<td style="text-align:right;">
8.400000
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:right;">
3.298000e+04
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Urban
</td>
<td style="text-align:left;">
min
</td>
<td style="text-align:right;">
21.500000
</td>
<td style="text-align:right;">
7.100000
</td>
<td style="text-align:right;">
7.200000
</td>
<td style="text-align:right;">
2.810600e+04
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Rural
</td>
<td style="text-align:left;">
sd
</td>
<td style="text-align:right;">
2.152720
</td>
<td style="text-align:right;">
1.197331
</td>
<td style="text-align:right;">
5.595007
</td>
<td style="text-align:right;">
9.905487e+03
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Urban
</td>
<td style="text-align:left;">
sd
</td>
<td style="text-align:right;">
2.620586
</td>
<td style="text-align:right;">
1.422427
</td>
<td style="text-align:right;">
9.101626
</td>
<td style="text-align:right;">
1.391053e+04
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Rural
</td>
<td style="text-align:left;">
var
</td>
<td style="text-align:right;">
4.634203
</td>
<td style="text-align:right;">
1.433601
</td>
<td style="text-align:right;">
31.304102
</td>
<td style="text-align:right;">
9.811868e+07
</td>
</tr>
<tr>
<td style="text-align:left;">
Mostly Urban
</td>
<td style="text-align:left;">
var
</td>
<td style="text-align:right;">
6.867472
</td>
<td style="text-align:right;">
2.023300
</td>
<td style="text-align:right;">
82.839597
</td>
<td style="text-align:right;">
1.935027e+08
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>project1 %&gt;% select_if(is.numeric) %&gt;% cor() %&gt;% kable()</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
PercentObese
</th>
<th style="text-align:right;">
PercentDiabetic
</th>
<th style="text-align:right;">
PercentBachelors
</th>
<th style="text-align:right;">
Medianincome
</th>
<th style="text-align:right;">
pctRural
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
PercentObese
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0.2598185
</td>
<td style="text-align:right;">
-0.2712604
</td>
<td style="text-align:right;">
-0.1254862
</td>
<td style="text-align:right;">
-0.1337214
</td>
</tr>
<tr>
<td style="text-align:left;">
PercentDiabetic
</td>
<td style="text-align:right;">
0.2598185
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
-0.1579260
</td>
<td style="text-align:right;">
-0.3207670
</td>
<td style="text-align:right;">
0.4902064
</td>
</tr>
<tr>
<td style="text-align:left;">
PercentBachelors
</td>
<td style="text-align:right;">
-0.2712604
</td>
<td style="text-align:right;">
-0.1579260
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
0.6320141
</td>
<td style="text-align:right;">
-0.2259000
</td>
</tr>
<tr>
<td style="text-align:left;">
Medianincome
</td>
<td style="text-align:right;">
-0.1254862
</td>
<td style="text-align:right;">
-0.3207670
</td>
<td style="text-align:right;">
0.6320141
</td>
<td style="text-align:right;">
1.0000000
</td>
<td style="text-align:right;">
-0.1925140
</td>
</tr>
<tr>
<td style="text-align:left;">
pctRural
</td>
<td style="text-align:right;">
-0.1337214
</td>
<td style="text-align:right;">
0.4902064
</td>
<td style="text-align:right;">
-0.2259000
</td>
<td style="text-align:right;">
-0.1925140
</td>
<td style="text-align:right;">
1.0000000
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>tidycor &lt;- project1 %&gt;% select_if(is.numeric) %&gt;% cor() %&gt;% as.data.frame %&gt;% 
    rownames_to_column %&gt;% pivot_longer(-1, names_to = &quot;name&quot;, 
    values_to = &quot;correlation&quot;)
tidycor %&gt;% ggplot(aes(rowname, name, fill = correlation)) + 
    geom_tile() + scale_fill_gradient2(low = &quot;red&quot;, high = &quot;blue&quot;) + 
    geom_text(aes(label = round(correlation, 2)), color = &quot;black&quot;, 
        size = 4) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + coord_fixed() + ggtitle(&quot;Correlation Matrix for TX County Data&quot;)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This table shows the correlations between each variable within the project 1 dataset. In blue/purple are the positive correlations between variables. The squares in red/pink show negative correlations. Percent Bachelors positively correlates with Median Household income, and negatively correlates with percent rural, percent diabetic, and percent obese. Percent rural positively correlates with percent diabetic, and negatively correlates with median income, percent bachelors, and percent obesity. Percent obese positively correlates with percent diabetic, but negatively correlates with median income, percent rural, and percent bachelors. These correlations helped to guide what visualizations that were chosen.</p>
<pre class="r"><code>project1 %&gt;% ggplot() + geom_point(aes(x = Medianincome, y = PercentBachelors, 
    color = `Rural/Urban`, )) + scale_x_continuous() + geom_smooth(method = &quot;lm&quot;, 
    se = FALSE, aes(x = Medianincome, y = PercentBachelors, color = `Rural/Urban`)) + 
    ggtitle(&quot;Percent Bachelors vs Median Income in Texas Counties&quot;) + 
    scale_x_continuous(labels = scales::dollar) + xlab(&quot;Median Household Income&quot;) + 
    ylab(&quot;% of County with Bachelors Degree&quot;) + scale_y_continuous(breaks = seq(0, 
    50, 10)) + scale_color_brewer(palette = &quot;Set1&quot;)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" />
This graph displays a scatterplot of Median Household Incomes of Texas counties with Percent of a county holding a bachelors degree. There is a positive relationship between having a higher percentage of people with a bachelors degree in a county and a higher median income as seen by the trendline. The “Mostly Urban” counties also have a trendline with a more positive slope compared to the “Mostly Rural” Counties. This indicates that the positive relationship between Percent bachelors and Median household income is stronger in Urban Counties than Rural Counties.</p>
<pre class="r"><code>project1 %&gt;% ggplot() + geom_smooth(method = &quot;lm&quot;, se = FALSE, 
    aes(x = PercentObese, y = PercentBachelors, color = `Rural/Urban`)) + 
    geom_point(aes(x = PercentObese, y = PercentBachelors, color = `Rural/Urban`, 
        size = Medianincome)) + scale_x_continuous() + ggtitle(&quot;Percent Bachelors vs Obesity Rate in Texas Counties&quot;) + 
    xlab(&quot;Obesity Rate (%)&quot;) + ylab(&quot;% of County with Bachelors Degree&quot;) + 
    scale_color_brewer(palette = &quot;Paired&quot;)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" />
This graph shows the relationship between Obesity Rate, % of a county with a bachelors degree, and median household income. There is a clear negative relationship between obesity rate and Percent bachelors degree. As % Bachelors decreases obesity rates increase as seen by the trendlines. The size of the points indicate miedian income as seen through the bigger points having higher educational attainment. There is also a difference btween Rural/Urban counties as Urban counties have a stronger relationship between obeisty and bachelors degree than rural counties as seen throught the differing slopes.</p>
<pre class="r"><code>project1 %&gt;% ggplot(aes(x = `Rural/Urban`, y = PercentDiabetic, 
    fill = `Rural/Urban`)) + geom_bar(stat = &quot;summary&quot;, fun.y = &quot;mean&quot;, 
    width = 0.7) + geom_errorbar(stat = &quot;summary&quot;, width = 0.5) + 
    theme(legend.position = &quot;none&quot;) + ggtitle(&quot;Mean Diabetic Percentage in Rural vs Urban Counties&quot;) + 
    scale_fill_brewer(palette = &quot;Set1&quot;)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" />
This graph shows a clear difference between Mostly Rural and Mostly Urban counties in the rates of diabetes. Urban counties on average have lower rates of Diabetes than Rural counties.</p>
<pre class="r"><code>clust_dat &lt;- project1 %&gt;% select(2:6)
sil_width &lt;- vector()
for (i in 2:10) {
    pam_fit &lt;- pam(clust_dat, k = i)
    sil_width[i] &lt;- pam_fit$silinfo$avg.width
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:10) + ggtitle(&quot;Silhouette Width vs Number of Clusters&quot;)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" />
This is a graph of silhouette width for the numeric data for project one. This graph shows that 2 clusters would be the optimal number of clusters as it has the highest silhouette width.</p>
<pre class="r"><code>pamproject1 &lt;- clust_dat %&gt;% pam(k = 2)
pamproject1</code></pre>
<pre><code>## Medoids:
##       ID PercentObese PercentDiabetic PercentBachelors Medianincome pctRural
## [1,] 177         31.4            11.3             15.5        42662 32.65641
## [2,] 251         29.1             9.1             16.3        58363 37.32707
## Clustering vector:
##   [1] 1 2 1 1 2 2 1 2 1 2 2 1 1 2 2 2 2 1 1 2 1 1 1 1 1 1 2 2 2 1 1 1 2 1 1 2 1
##  [38] 1 2 1 1 1 2 1 1 2 1 1 2 2 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 2 1 2 1 1 1 2
##  [75] 2 1 1 1 2 1 1 1 2 2 1 2 2 2 1 1 2 1 1 2 1 1 1 2 1 2
##  [ reached getOption(&quot;max.print&quot;) -- omitted 154 entries ]
## Objective function:
##    build     swap 
## 5917.180 5267.462 
## 
## Available components:
##  [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
##  [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;       &quot;data&quot;</code></pre>
<pre class="r"><code>project1 %&gt;% count(`Rural/Urban`)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   `Rural/Urban`     n
##   &lt;chr&gt;         &lt;int&gt;
## 1 Mostly Rural    136
## 2 Mostly Urban    118</code></pre>
<pre class="r"><code>pamclust &lt;- clust_dat %&gt;% mutate(cluster = as.factor(pamproject1$clustering))
confmat &lt;- pamclust %&gt;% mutate(RuralUrban = project1$`Rural/Urban`) %&gt;% 
    group_by(RuralUrban) %&gt;% count(cluster) %&gt;% pivot_wider(names_from = &quot;cluster&quot;, 
    values_from = &quot;n&quot;, values_fill = list(n = 0))
confmat</code></pre>
<pre><code>## # A tibble: 2 x 3
## # Groups:   RuralUrban [2]
##   RuralUrban     `1`   `2`
##   &lt;chr&gt;        &lt;int&gt; &lt;int&gt;
## 1 Mostly Rural    93    43
## 2 Mostly Urban    70    48</code></pre>
<p>Based on the clustering data it does not seem that the counties are clustering based on their rural/urban distinction. There must be a different factor that accounts for the clustering data seen. The first table shows the counts of Mostly Rural and Mostly Urban Counties.</p>
<pre class="r"><code>plot(pamproject1)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /><img src="/project1_files/figure-html/unnamed-chunk-12-2.png" width="672" style="display: block; margin: auto;" />
This graph indicated the average silhouette width is .58 which can be interpreted as a resonable structure has been found among the clusters.</p>
<pre class="r"><code>project1 %&gt;% mutate(cluster = pamproject1$clustering) %&gt;% rename_all(function(x) sub(&quot;_&quot;, 
    &quot;.&quot;, x)) %&gt;% select_if(is.numeric) %&gt;% group_by(cluster) %&gt;% 
    mutate(n = n()) %&gt;% group_by(cluster, n) %&gt;% summarize_all(.funs = list(mean = mean, 
    median = median, sd = sd), na.rm = T) %&gt;% pivot_longer(contains(&quot;_&quot;)) %&gt;% 
    separate(name, sep = &quot;_&quot;, into = c(&quot;variable&quot;, &quot;stat&quot;)) %&gt;% 
    pivot_wider(names_from = &quot;variable&quot;, values_from = &quot;value&quot;) %&gt;% 
    arrange(stat) %&gt;% kable()</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
cluster
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:left;">
stat
</th>
<th style="text-align:right;">
PercentObese
</th>
<th style="text-align:right;">
PercentDiabetic
</th>
<th style="text-align:right;">
PercentBachelors
</th>
<th style="text-align:right;">
Medianincome
</th>
<th style="text-align:right;">
pctRural
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
163
</td>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
30.177914
</td>
<td style="text-align:right;">
11.149693
</td>
<td style="text-align:right;">
16.400000
</td>
<td style="text-align:right;">
42404.810
</td>
<td style="text-align:right;">
58.78728
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
91
</td>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
29.865934
</td>
<td style="text-align:right;">
10.279121
</td>
<td style="text-align:right;">
22.859341
</td>
<td style="text-align:right;">
61781.088
</td>
<td style="text-align:right;">
49.66828
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
163
</td>
<td style="text-align:left;">
median
</td>
<td style="text-align:right;">
29.700000
</td>
<td style="text-align:right;">
11.200000
</td>
<td style="text-align:right;">
16.100000
</td>
<td style="text-align:right;">
42650.000
</td>
<td style="text-align:right;">
59.62572
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
91
</td>
<td style="text-align:left;">
median
</td>
<td style="text-align:right;">
29.500000
</td>
<td style="text-align:right;">
10.300000
</td>
<td style="text-align:right;">
20.500000
</td>
<td style="text-align:right;">
58363.000
</td>
<td style="text-align:right;">
45.72031
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
163
</td>
<td style="text-align:left;">
sd
</td>
<td style="text-align:right;">
2.281245
</td>
<td style="text-align:right;">
1.486871
</td>
<td style="text-align:right;">
5.163954
</td>
<td style="text-align:right;">
4995.741
</td>
<td style="text-align:right;">
30.62114
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
91
</td>
<td style="text-align:left;">
sd
</td>
<td style="text-align:right;">
2.556092
</td>
<td style="text-align:right;">
1.257733
</td>
<td style="text-align:right;">
9.197499
</td>
<td style="text-align:right;">
10763.190
</td>
<td style="text-align:right;">
33.45865
</td>
</tr>
</tbody>
</table>
<p>The table above displays summary statistics for each cluster.</p>
<pre class="r"><code>clust_dat %&gt;% mutate(cluster = as.factor(pamproject1$clustering)) %&gt;% 
    ggpairs(columns = 1:5, aes(color = cluster))</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" />
This GGpairs plot shows the two different clusters as red and blue. From this visualization median income is the main differentiating factor between the two clusters.</p>
<pre class="r"><code>pamclust &lt;- clust_dat %&gt;% mutate(cluster = as.factor(pamproject1$clustering))
pamclust %&gt;% mutate(`Rural/Urban` = project1$`Rural/Urban`) %&gt;% 
    ggplot(aes(PercentObese, PercentBachelors, color = `Rural/Urban`, 
        shape = cluster)) + geom_point() + scale_color_brewer(palette = &quot;Set1&quot;) + 
    ggtitle(&quot;Percent Bachelors vs Obesity with Cluster Data&quot;) + 
    ylab(&quot;% of County with Bachelors Degree&quot;) + xlab(&quot;Obesity Rate (%)&quot;)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" />
This visualization does not show any clear distinction between clusters. This means that the clusters are more likely based on variable(s) that are not % Bachelors, % Obese, or Rural/Urban.</p>
<pre class="r"><code>pamclust %&gt;% mutate(`Rural/Urban` = project1$`Rural/Urban`) %&gt;% 
    ggplot(aes(PercentBachelors, Medianincome, color = `Rural/Urban`, 
        shape = cluster)) + geom_point() + scale_color_brewer(palette = &quot;Set1&quot;) + 
    ggtitle(&quot;Percent Bachelors vs Median Income with Cluster Data&quot;) + 
    scale_y_continuous(breaks = seq(20000, 1e+05, 10000), labels = scales::dollar) + 
    geom_abline(slope = 1, intercept = 50000) + xlab(&quot;% of County with Bachelors Degree&quot;) + 
    ylab(&quot;Median Household Income&quot;)</code></pre>
<p><img src="/project1_files/figure-html/unnamed-chunk-16-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>This second visualization captures the distinction between the clusters. The clusters seem to be determined by Median Household Income with the cutoff between clusters occuring around $50,000. Median Income seems to be the main differentiating factor between these two clusters.</p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
s="r"><code>library(plotROC)
ROCplot&lt;-ggplot(project2)+geom_roc(aes(d=y, m=probs), n.cuts=0)
ROCplot</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7285999</code></pre>
<pre class="r"><code>set.seed(1234) 
k=10
data&lt;-project2[sample(nrow(project2)),]
folds&lt;-cut(seq(1:nrow(project2)),breaks=k, labels=F)
diags&lt;-NULL
for(i in 1:k){
  train&lt;-data[folds!=i,]
  test&lt;-data[folds==i,]
  truth&lt;-test$y
  fit&lt;-glm(y~Lifeexpt+pctinsufficientsleep, data=train, family=&quot;binomial&quot;)
  probs&lt;-predict(fit, newdata=test, type=&quot;response&quot;)
  diags&lt;-rbind(diags, class_diag(probs,truth))
}
summarize_all(diags, mean)</code></pre>
<pre><code>##    acc      sens      spec       ppv       auc
## 1 0.65 0.6094505 0.6858275 0.6665967 0.7187925</code></pre>
<p>This logistic regression is prediciting if a county is Mostly Urban or Mostly Rural based on life expectancy and percent of the population getting insufficient sleep. In the model Mostly Rural and Mostly Urban are a binary classification with 1 representing Mostly Urban and 0 representing Mostly Rural. These coefficient show that going up 1 year in life expectancy increases the log-odds by .204 and going up by 1% of insufficent sleep increases the log-odds score of being a Mostly Urban county by .462.The coefficient when exponentiated show that an increase of 1 year of life expectancy increases the odds of being a Mostly Urban county by 1.27 and a 1% increase of insufficent sleep raises the odds of being a Mostly Urban county by 1.587.<br />
The TPR is .627
The TNR is .686
The PPV is .667
The ROC plot visualizes the tradeoff between sensitivity and specificity. Based on the graph the model is predicting fairly, but it could be improved. The AUC has a value of .726 which means that life expectancy and percent insufficient sleep are fair predictors of whether a county is mostly urban or mostly rural.
The 10-fold cross validation had an accuracy of .65, a sensitivity of .609, a specificity of .685, a ppv of .667, and an auc of .719. These values were slightly lower than the in-sample model. The results from the 10-fold cross validation do not differ greatly from the original model showing that the original model was not overfitting the data significantly.</p>
</div>
<div id="linear-lasso-regression" class="section level1">
<h1>Linear LASSO Regression</h1>
<pre class="r"><code>library(glmnet)

fulldata%&gt;%select(County,`Life Expectancy`,`% Adults with Obesity`,`% Physically Inactive`,`% Smokers`,`% Food Insecure`,`% Uninsured`,`% Adults with Diabetes`,`Percent of adults with a bachelor&#39;s degree or higher, 2014-18`, `Median Household Income`, `% Insufficient Sleep`,`% Excessive Drinking`,`% Rural`)-&gt;project2.1
project2.1%&gt;% na.omit()-&gt;project2.1
project2.1%&gt;% rename(Lifeexpt=`Life Expectancy`)%&gt;% rename(pctObese=`% Adults with Obesity`)%&gt;% rename(pctInactive=`% Physically Inactive`)%&gt;% rename(pctFDInsecure=`% Food Insecure`)%&gt;% rename(pctSmokers=`% Smokers`)%&gt;% rename(pctUninsured=`% Uninsured`)%&gt;% rename(pctDiabetes=`% Adults with Diabetes`)%&gt;% rename(pctBachelors=`Percent of adults with a bachelor&#39;s degree or higher, 2014-18`)%&gt;% rename(medianincome=`Median Household Income`)%&gt;% rename(pctinsufficientsleep=`% Insufficient Sleep`)%&gt;% rename(pctRural=`% Rural`)%&gt;% rename(pctexcessdrinking=`% Excessive Drinking`)-&gt;project2.1
project2.1%&gt;% select(2:12)-&gt;project2.1


y&lt;-as.matrix(project2.1$Lifeexpt)
x&lt;-project2.1%&gt;% select(-Lifeexpt)%&gt;% mutate_all(scale)%&gt;% as.matrix()
cv&lt;-cv.glmnet(x,y) 
lasso&lt;-glmnet(x,y, lambda = cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 11 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                               s0
## (Intercept)          77.45919690
## pctObese              .         
## pctInactive           .         
## pctSmokers            .         
## pctFDInsecure        -0.65162370
## pctUninsured          0.01433402
## pctDiabetes           .         
## pctBachelors          0.80363892
## medianincome          .         
## pctinsufficientsleep  .         
## pctexcessdrinking     .</code></pre>
<pre class="r"><code>fit1.0&lt;-lm(Lifeexpt~pctFDInsecure+pctBachelors, data = project2.1)
summary(fit1.0)</code></pre>
<pre><code>##
## Call:
## lm(formula = Lifeexpt ~ pctFDInsecure + pctBachelors,
data = project2.1)
##
## Residuals:
## Min 1Q Median 3Q Max
## -5.9582 -0.8841 -0.1142 0.7497 11.2166
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 78.62517 0.59224 132.760 &lt; 2e-16 ***
## pctFDInsecure -0.27520 0.03440 -8.000 5.74e-14 ***
## pctBachelors 0.15113 0.01653 9.145 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 1.912 on 234 degrees of freedom
## Multiple R-squared: 0.3788, Adjusted R-squared: 0.3735
## F-statistic: 71.34 on 2 and 234 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>summary(fit1)</code></pre>
<pre><code>##
## Call:
## lm(formula = Lifeexpt ~ pctObese_c * pctSmokers_c *
pctFDInsecure_c *
## pctexcessdrinking_c, data = project2)
##
## Residuals:
## Min 1Q Median 3Q Max
## -6.2359 -1.0366 -0.1286 1.0374 10.6818
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 77.194298 0.157557 489.944 &lt; 2e-16
## pctObese_c -0.069386 0.032830 -2.114 0.035679
## pctSmokers_c -0.526837 0.119198 -4.420 1.55e-05
## pctFDInsecure_c -0.117016 0.047041 -2.488 0.013602
## pctexcessdrinking_c -0.066368 0.098937 -0.671 0.503044
## pctObese_c:pctSmokers_c 0.040947 0.024289 1.686 0.093239
## pctObese_c:pctFDInsecure_c -0.003714 0.008888 -0.418
0.676403
## pctSmokers_c:pctFDInsecure_c 0.014818 0.031560 0.470
0.639162
## pctObese_c:pctexcessdrinking_c -0.010845 0.018142 -0.598
0.550612
## pctSmokers_c:pctexcessdrinking_c -0.193368 0.050845
-3.803 0.000185
## pctFDInsecure_c:pctexcessdrinking_c 0.100632 0.030323
3.319 0.001058
## pctObese_c:pctSmokers_c:pctFDInsecure_c 0.003717
0.005457 0.681 0.496444
## pctObese_c:pctSmokers_c:pctexcessdrinking_c -0.003599
0.008180 -0.440 0.660363
## pctObese_c:pctFDInsecure_c:pctexcessdrinking_c 0.004489
0.005380 0.834 0.404983
## pctSmokers_c:pctFDInsecure_c:pctexcessdrinking_c
-0.002156 0.016035 -0.134 0.893149
##
pctObese_c:pctSmokers_c:pctFDInsecure_c:pctexcessdrinking_c
0.003756 0.003092 1.215 0.225770
##
## (Intercept) ***
## pctObese_c *
## pctSmokers_c ***
## pctFDInsecure_c *
## pctexcessdrinking_c
## pctObese_c:pctSmokers_c .
## pctObese_c:pctFDInsecure_c
## pctSmokers_c:pctFDInsecure_c
## pctObese_c:pctexcessdrinking_c
## pctSmokers_c:pctexcessdrinking_c ***
## pctFDInsecure_c:pctexcessdrinking_c **
## pctObese_c:pctSmokers_c:pctFDInsecure_c
## pctObese_c:pctSmokers_c:pctexcessdrinking_c
## pctObese_c:pctFDInsecure_c:pctexcessdrinking_c
## pctSmokers_c:pctFDInsecure_c:pctexcessdrinking_c
##
pctObese_c:pctSmokers_c:pctFDInsecure_c:pctexcessdrinking_c
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 2.004 on 221 degrees of freedom
## Multiple R-squared: 0.3557, Adjusted R-squared: 0.312
## F-statistic: 8.135 on 15 and 221 DF, p-value: 1.363e-14</code></pre>
</div>
<div id="binary-lasso-regression" class="section level1">
<h1>Binary Lasso Regression</h1>
<pre class="r"><code>a&lt;-as.matrix(project2$y)
b&lt;-model.matrix(y~pctObese+pctInactive+pctSmokers+pctFDInsecure+pctUninsured+pctDiabetes+pctBachelors+medianincome+pctinsufficientsleep+pctexcessdrinking, data=project2)[,-1]
cv&lt;-cv.glmnet(b,a,family=&quot;binomial&quot;) 
lasso&lt;-glmnet(b,a,family=&quot;binomial&quot;,lambda=cv$lambda.1se) 
coef(lasso)</code></pre>
<pre><code>## 11 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                s0
## (Intercept)          -11.89719842
## pctObese               .         
## pctInactive            .         
## pctSmokers             .         
## pctFDInsecure         -0.11429013
## pctUninsured           .         
## pctDiabetes            .         
## pctBachelors           0.04199906
## medianincome           .         
## pctinsufficientsleep   0.36574083
## pctexcessdrinking      0.06158514</code></pre>
<pre class="r"><code>set.seed(1234) 
k=10
data&lt;-project2[sample(nrow(project2)),]
folds&lt;-cut(seq(1:nrow(project2)),breaks=k, labels=F)
diags&lt;-NULL
for(i in 1:k){
  train&lt;-data[folds!=i,]
  test&lt;-data[folds==i,]
  truth&lt;-test$y
  fit&lt;-glm(y~pctFDInsecure+pctBachelors+pctinsufficientsleep+pctexcessdrinking, data=train, family=&quot;binomial&quot;)
  probs&lt;-predict(fit, newdata=test, type=&quot;response&quot;)
  diags&lt;-rbind(diags, class_diag(probs,truth))
}
summarize_all(diags, mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.7311594 0.7231707 0.7433949 0.7400505 0.8120656</code></pre>
<p>I chose to compare predict both a binary variable and a continuous variable.The binary variable chosen to predict was if a county was Mostly Urban or Mostly Rural, while the continous varible to predict was life expectancy.</p>
<p>In the Linear Lasso Regression the variables that were retained were percent Obesity, percent Inactive, percent Food insecure, percent uninsured, percent Bachelor’s degree, median income, percent insufficient sleep, and percent excess drinking. A linear regression with these models provided a residual standard error of 1.9 which is lower compared to the previous linear model predicting life expectancy which had a residual standard error of 2.0</p>
<p>The variables that were retained in the Binary lasso regression were percent Food Insecure, percent Bachelors degree, percent insufficient sleep, and percent excess drinking. These variables were then used in 10-fold cross validation. The model had an accuracy of .731, and sensitivity of .723, a specificity of .743, a ppv of .740, and an significantly higher AUC of .81 when compared to the previous logisitc regression AUC of .717. This new model computed from variables from the LASSO regession is classified as a good AUC. This model is predicting whether a county is urban or rural much better.</p>
<p>…</p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
